### ISSUE TITLE
Custom enclosingClass when calling makeIOLogger?

### ISSUE THREAD

**Issue by gvolpe** [LEGO/woof#17] opened 2021-12-20 18:10 UTC
Hi,

I was wondering if you would consider a custom (probably optional) argument for `makeIOLogger` so that the value of `enclosingClass` is not computed [via macro](https://github.com/LEGO/woof/blob/main/modules/core/shared/src/main/scala/org/legogroup/woof/Logger.scala#L50)?

My use case is that I already have a `Logger` interface all my services use, so I want to abstract over any implementation detail (woof could be just one of many interpreters). At the moment, the "enclosing class" is the following one, which is not pretty:

``` 
trading.lib.Logger$._$$anon
```

Ideally, though, this should represent the package of each service instead of this common package name.

For reference, here's how I instantiate it in my `Logger`:

```scala
val make: IO[Logger[IO]] =
  given Filter  = Filter.everything
  given Printer = ColorPrinter()
  WoofLogger.makeIoLogger(Output.fromConsole).map(from[IO])
```

Or maybe there's a way to make my logger constructor aware of the right enclosing class via macro?

Thanks!

**Comment by hejfelix** [comment] 2021-12-20 18:29
The enclosingClass is not decided on construction, rather at the callsite of each logging call (`info`,`debug`,etc.). This is very much by design to allow injecting the logger and having a well behaved `Local` instance. Are you doing free monads? I'm trying to understand how this would happen.
If you are wrapping the method in any way, _the wrapping method has to also be inlined_! This also has the implication that it can't be behind an interface because that'd be a dynamic dispatch situation (as far as I understand).

**Comment by hejfelix** [comment] 2021-12-20 18:37
> woof could be just one of many interpreters

For the reasons I mention above, I am afraid you might not be able to abstract over woof at all. This approach falls apart if the macro calls are unable to be inlined. The closest thing that comes to my mind is what I'm doing in the SLF4J interop:

https://github.com/LEGO/woof/blob/main/modules/slf4j/src/main/scala/org/legogroup/woof/slf4j/WoofLogger.scala#L15-L29

but it ain't pretty, and it's using reflection. If that works for you, you can just do steal that directly :)

**Comment by gvolpe** [comment] 2021-12-20 18:38
The implementation of my `Logger.from` is this one:

```scala
def from[F[_]](log: WoofLogger[F]): Logger[F] = new:
  inline def info(str: => String): F[Unit]  = log.info(str)
  inline def error(str: => String): F[Unit] = log.error(str)
  inline def debug(str: => String): F[Unit] = log.debug(str)
  inline def warn(str: => String): F[Unit]  = log.warn(str)
```

I also tried the following combination but I can't say I fully understand how the compiler interprets the `inline` keyword 😄 

```scala
inline def from[F[_]](log: WoofLogger[F]): Logger[F] = new:
  def info(str: => String): F[Unit]  = log.info(str)
  def error(str: => String): F[Unit] = log.error(str)
  def debug(str: => String): F[Unit] = log.debug(str)
  def warn(str: => String): F[Unit]  = log.warn(str)

inline def make: IO[Logger[IO]] =
  given Filter  = Filter.everything
  given Printer = ColorPrinter()
  WoofLogger.makeIoLogger(Output.fromConsole).map(from[IO](_))
```

Both produce the same results as without inlining anything.

**Comment by hejfelix** [comment] 2021-12-20 18:39
I believe the string argument also has to have the inline keyword

**Comment by gvolpe** [comment] 2021-12-20 18:39
Ah okay, just seeing the other message. That's what I was afraid of by reading why woof's logger is an open class :/

**Comment by hejfelix** [comment] 2021-12-20 18:42
Yeah, it's a hefty price, but you also win some things (e.g. scala.js support). I think doing reflection like I mentioned above would definitely work but then scala.js is out of the picture.

**Comment by gvolpe** [comment] 2021-12-20 18:44
In my case, I don't care about Scala.js, but reflection is really bad, I'd rather not do that. I think a way to customize the `Logger` would go a long way (e.g. Odin [allows some customization](https://github.com/valskalla/odin#contramap-and-filter)) but that's just my 2 cents :)

Thanks a lot for your quick feedback, appreciate it 🙇🏽

**Comment by hejfelix** [comment] 2021-12-20 18:59
Thanks for pointing Odin out, I hadn't seen this library (it's scary impressive xD). I also didn't know `sourcecode` was released for Scala 3 :D

**Comment by hejfelix** [comment] 2021-12-20 20:34
@gvolpe https://github.com/LEGO/woof/tree/feature/implicit-macro I made an attempt to extract a trait here, it looks pretty promising to me

**Comment by gvolpe** [comment] 2021-12-21 10:57
@hejfelix I think it looks good. I'd add a test with a custom `LogInfo` instance in scope to verify its behavior.

**Comment by hejfelix** [comment] 2021-12-21 13:44
Thanks, unfortunately it won't be reviewed soon because my colleagues are on vacation xD look forward to 2022, I guess 😁🎉

**Comment by gvolpe** [comment] 2021-12-21 14:41
No rush, thanks for looking into it and have a happy holidays you too :)

**Comment by hejfelix** [comment] 2022-01-03 08:53
We extracted the macro as a given which allows injecting all `LogInfo` at call site. Will close this :) Release coming soon

**Closed by hejfelix** 2022-01-03 08:53 UTC
